spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pineapple?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 关键：告诉 Redisson 去哪加载配置
  redisson:
    config: classpath:redisson.yml

  # RocketMQ（可选）
  rocketmq:
    name-server: 127.0.0.1:9876
    producer:
      group: point-producer-group

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      timeout: 5s
      host: 1.94.63.63
      port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml

jwt:
  secret: yourSecretKey
  expire: 86400 # token

server:
  port: 9022

logging:
  level:
    com.pine: info
